# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bee55d2e55fc19d75419301bc95d63274d1c999a264b33416c811f4a61671e6aa1930cccc74a6a3f2bd0c83e177f29de7ef7aed1ed1242e15922750f10f3816d

test:
  secret_key_base: 1b70297954445dbb0f0ca61a4d95606f62803978e99708f133df801e439c6d1774d277d2f41f8ac45222a4130d96bf069b7a6b228c3985f37e2150ab566280c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
